<<<<<<< HEAD
<<<<<<< HEAD
{{- if .Values.fluentbit.enabled }}
=======
{{- if and (not .Values.loki.enabled) (not .Values.promtail.enabled) (or .Values.elasticsearchKibana.enabled .Values.fluentbit.enabled) }}
>>>>>>> 69cfa70b (update to meet standards)
=======
{{- if and (not .Values.loki.enabled) (not .Values.promtail.enabled) (or .Values.elasticsearchKibana.enabled .Values.fluentbit.enabled) }}
>>>>>>> 8e32a7ad (update to meet standards)
{{- if ( include "imagePullSecret" . ) }}
apiVersion: v1
kind: Secret
metadata:
  name: private-registry
  namespace: fluentbit
  labels:
    app.kubernetes.io/name: fluentbit
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
{{- end }}
