{{- $logOldValues := default dict .Values.logging -}}
{{- $logValues := merge $logOldValues .Values.elasticsearchKibana -}}
{{- if and (eq (include "checkGitRef" $logValues) "true") (not .Values.offline) ( $logValues.enabled ) }}
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: elasticsearch-kibana
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: elasticsearch-kibana
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
spec:
  interval: {{ .Values.flux.interval }}
  url: {{ $logValues.git.repo }}
  ref:
    {{- include "validRef" $logValues.git | nindent 4 }}
  {{ include "gitIgnore" . }}
  {{- include "gitCreds" . | nindent 2 }}
{{- end }}
