{{- if and .Values.kiali.enabled .Values.kiali.sso.enabled (or .Values.sso.certificate_authority (dig "certificateAuthority" "cert" false .Values.sso))  }}
# Kiali needs a specifically named configmap.
# https://kiali.io/docs/configuration/authentication/openid/#using-an-openid-provider-with-a-self-signed-certificate
apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali-cabundle
  namespace: kiali
data:
  openid-server-ca.crt: {{ default (dig "certificateAuthority" "cert" "" .Values.sso) .Values.sso.certificate_authority | quote }}
{{- end }}