{{- if and  .Values.addons.sonarqube.enabled  .Values.addons.sonarqube.sso.enabled dig "certificateAuthority" "cert" .Values.sso.certificate_authority .Values.sso }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ dig "certificateAuthority" "secretName" .Values.sso.secretName .Values.sso }}
  namespace: sonarqube
type: Opaque
data:
  ca.pem: {{ dig "certificateAuthority" "cert" .Values.sso.certificate_authority .Values.sso | b64enc }}
{{- end }}