include:
  - project: 'big-bang/pipeline-templates/pipeline-templates'
    ref: 'oscal-mr'
    file: '/pipelines/bigbang-package.yaml' 
variables:
  PIPELINE_REPO_BRANCH: 'oscal-mr'
  DEBUG_ENABLED: "true"
  MULTI_NODE: "true"
  BB_PROJECT_ID: 12985
  CI_PROJECT_NAME: "istio"

