include:
  - project: 'platform-one/big-bang/pipeline-templates/pipeline-templates'
    ref: '920-istio-version-check'
    file: '/pipelines/bigbang.yaml'
variables:
  PIPELINE_REPO_BRANCH: '920-istio-version-check' 
