include:
  - project: 'platform-one/big-bang/pipeline-templates/pipeline-templates'
    ref: neuvector-additions
    file: '/pipelines/bigbang.yaml'
variables:
  PIPELINE_REPO_BRANCH: 'neuvector-additions'
