include:
  - project: 'platform-one/big-bang/pipeline-templates/pipeline-templates'
    ref: 1152-rke2-tags
    file: '/pipelines/bigbang.yaml'
variables:
  PIPELINE_REPO_BRANCH: 1152-rke2-tags
  DEBUG_ENABLED: "true"