include:
  - project: 'platform-one/big-bang/pipeline-templates/pipeline-templates'
    ref: add-timeout-10m-for-gluon
    file: '/pipelines/bigbang.yaml'
variables:
  PIPELINE_REPO_BRANCH: "add-timeout-10m-for-gluon"
