include:
  - project: 'big-bang/pipeline-templates/pipeline-templates'
    ref: 'master'
    file: '/pipelines/bigbang.yaml'
variables:
  MULTI_NODE: "true"
  DEBUG_ENABLED: "true"
  CI_DEFAULT_BRANCH: 'np-test-values'
  PIPELINE_REPO_BRANCH: 'master'
