{{- if and (eq .Values.addons.minio.sourceType "git") (not .Values.offline) .Values.addons.minio.enabled }}
{{- $gitCredsDict := dict
  "name" "minio"
  "packageGitScope" .Values.addons.minio.git
  "outerScope" .
  "releaseName" $.Release.Name
}}
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: minio
  namespace: {{ .Release.Namespace }}
spec:
  interval: {{ .Values.flux.interval }}
  url: {{ .Values.addons.minio.git.repo }}
  ref:
    {{- include "validRef" .Values.addons.minio.git | nindent 4 }}
  {{ include "gitIgnore" . }}
  {{- include "gitCreds" $gitCredsDict | nindent 2 }}
{{- end }}
