{{- define "bigbang.defaults.neuvector" -}}
# hostname is deprecated and replaced with domain. But if hostname exists then use it.
domain: {{ default .Values.domain .Values.hostname }}

istio:
  enabled: {{ .Values.istio.enabled }}
  neuvector:
    gateways:
    - istio-system/{{ default "public" .Values.neuvector.ingress.gateway }}

monitoring:
  enabled: {{ .Values.monitoring.enabled }}

{{- if .Values.istio.enabled }}
manager:
  env:
    ssl: false
{{- end }}

networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}
  controlPlaneCidr: {{ .Values.networkPolicies.controlPlaneCidr }}
  ingressLabels:
    {{- $gateway := default "public" .Values.neuvector.ingress.gateway }}
    {{- $default := dict "app" (dig "gateways" $gateway "ingressGateway" nil .Values.istio) "istio" nil }}
    {{- toYaml (dig "values" "gateways" $gateway "selector" $default .Values.istio) | nindent 4 }}
{{- end }}

{{- /* Create secret */ -}}
{{- if .Values.neuvector.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.neuvector "name" "neuvector" "defaults" (include "bigbang.defaults.neuvector" .)) }}
{{- end }}
