{{- /* Used for pulling images from custom registries.  One per namespace */ -}}
{{- /* registryCredentials are required via schema; generate secrets if required dockerconfigjson inputs are present */ -}}
{{- if .Values.registryCredentials -}}
{{- /* registryCredentials can be a list or a map */ -}}
{{- $credType := typeOf .Values.registryCredentials -}}
{{- /* create secrets if map or first map in list has required dockerconfigjson inputs*/ -}}
{{- if or 
  (and (eq $credType "map[string]interface {}") .Values.registryCredentials.registry .Values.registryCredentials.username .Values.registryCredentials.password)
  (and (eq $credType "[]interface {}") (first .Values.registryCredentials).registry (first .Values.registryCredentials).username (first .Values.registryCredentials).password) 
-}}
{{- range $ns := compact (splitList " " (include "uniqueNamespaces" (merge (dict "default" true) .))) -}}
apiVersion: v1
kind: Secret
metadata:
  name: private-registry
  namespace: {{ $ns }}
  labels:
    app.kubernetes.io/name: private-registry
    {{- include "commonLabels" $ | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" $ }}
---
{{- end -}}
{{- end -}}
{{- end -}}