{{- if (not .Values.offline) }}
{{- $name := "gitlab" }}
{{- with .Values.addons.gitlab -}}
{{- if and (eq .sourceType "git") .enabled }}
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/component: "developer-tools"
    {{- include "commonLabels" . | nindent 4}}
spec:
  interval: {{ .Values.flux.interval }}
  url: {{ .git.repo }}
  ref:
    {{- include "validRef" .git | nindent 4 }}
  {{- if .git.existingSecret }}
  secretRef:
    name: {{ .git.existingSecret }}
  {{- else if .git.credentials }}
  secretRef:
    name: {{ $.Release.Name }}-{{ $name }}-git-credentials
  {{- else }}
  {{- include "gitCreds" . | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
