{{- $pkg := "fortify" }}
{{- $gitCredsSecretDict := dict
  "name" $pkg
  "targetScope" (get .Values.addons $pkg).git
  "releaseName" $.Release.Name
  "releaseNamespace" $.Release.Namespace
}}
{{- include "gitCredsSecret" $gitCredsSecretDict | nindent 0 -}}
