{{- /* Used for creating secret for the package's HelmRelease */ -}}
{{- range $pkg, $vals := .Values.packages -}}
{{- if (dig "enabled" true $vals) -}}
{{- $pkg = include "resourceName" $pkg -}}
apiVersion: v1
kind: Secret
metadata:
  name: bigbang-values
  namespace: {{ dig "namespace" "name" $pkg $vals }}
  labels:
    {{- include "commonLabels" $ | nindent 4 }}
type: Opaque
stringData:
  values.yaml: |
    bb_domain: {{ $.Values.domain }}
    bb_istio:
      enabled: {{ $.Values.istio.enabled }}
    bb_monitoring:
      enabled: {{ $.Values.monitoring.enabled }}
    bb_gatekeeper:
      enabled: {{ $.Values.gatekeeper.enabled }}
    bb_networkPolicies:
      enabled: {{ $.Values.networkPolicies.enabled }}
      controlPlaneCidr: {{ $.Values.networkPolicies.controlPlaneCidr }}
---
{{ end -}}
{{- end -}}