{{- /* Used for GitOps on a package's Helm chart */ -}}
{{- range $pkg, $vals := .Values.packages -}}
{{- if and (dig "enabled" true $vals) ($vals.git) -}}
{{- $pkg = include "resourceName" $pkg -}}
{{- $defaults := $.Files.Get (printf "defaults/%s.yaml" $pkg) -}}
{{- if $defaults -}}
{{- $vals := merge $vals ($defaults | fromYaml).package -}}
{{- end -}}
{{- $gitCredsSecretDict := dict
  "name" $pkg
  "targetScope" $vals
  "releaseName" $.Release.Name
  "releaseNamespace" $.Release.Namespace
}}
{{- include "gitCredsSecret" $gitCredsSecretDict | nindent 0 -}}
---
{{- end -}}
{{- end -}}