{{- /* Used for including the default imagepullsecret */ -}}
{{- range $pkg, $vals := .Values.packages -}}
{{- if and (dig "enabled" false $vals) $vals.imagepullsecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: private-registry
  namespace: name: {{ dig "namespace" "name" $pkg $vals }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
---
{{ end -}}
{{- end -}}