{{- /* Used for deploying a package using Kustomize */ -}}
{{- range $pkg, $vals := .Values.packages -}}
{{- if and (dig "enabled" true $vals) $vals.kustomize -}}
{{- $pkg := include "resourceName" $pkg -}}
{{- $defaults := $.Files.Get (printf "defaults/%s.yaml" $pkg) -}}
{{- if $defaults -}}
{{- $vals := merge $vals ($defaults | fromYaml).package -}}
{{- end -}}
{{- $fluxSettings := merge (dig "flux" dict $vals) $.Values.flux -}}
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: {{ $pkg }}
  namespace: {{ dig "namespace" "name" $pkg $vals }}
  labels:
    app.kubernetes.io/name: {{ $pkg }}
    {{- include "commonLabels" $ | nindent 4 }}
spec:
  interval: 10m
  path: {{ dig "git" "path" "" $vals }}
  sourceRef:
    kind: GitRepository
    name: {{ $pkg }}
    namespace: {{ dig "namespace" "name" $pkg $vals }}
  prune: true
---
{{ end -}}
{{- end -}}