{{- /* Used for deploying a package using Kustomize */ -}}
{{- range $pkg, $vals := .Values.packages -}}
{{- if and (dig "enabled" true $vals) $vals.kustomize -}}
{{- $pkg := include "resourceName" $pkg -}}
{{- $defaults := $.Files.Get (printf "defaults/%s.yaml" $pkg) -}}
{{- if $defaults -}}
{{- $vals := merge $vals ($defaults | fromYaml).package -}}
{{- end -}}
{{- $fluxSettings := merge (dig "flux" dict $vals) $.Values.flux -}}
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: {{ $pkg }}
  namespace: {{ dig "namespace" "name" $pkg $vals }}
  labels:
    app.kubernetes.io/name: {{ $pkg }}
    {{- include "commonLabels" $ | nindent 4 }}
spec:
  targetNamespace: {{ dig "namespace" "name" $pkg $vals }}
  path: {{ dig "git" "path" "" $vals }}
  sourceRef:
    kind: GitRepository
    name: {{ $pkg }}
    namespace: {{ dig "namespace" "name" $pkg $vals }}
  prune: true
  {{- toYaml $fluxSettings | nindent 2 }}
  postBuild:
    substituteFrom:
    - name: {{ $pkg }}-values
      kind: Secret

  {{- /* Always wait on policy enforcement */ -}}
  {{- $gatekeeperDep := $.Values.gatekeeper.enabled -}}
  {{- $kyvernoDep := $.Values.kyvernopolicies.enabled -}}
  {{- /* Wait on istio if sidecar is enabled */ -}}
  {{- $istioDep := (and $.Values.istio.enabled (dig "istio" "injection" true $vals)) -}}
  {{- if or $gatekeeperDep $kyvernoDep $istioDep }}
  dependsOn:
    {{- if $gatekeeperDep }}
    - name: gatekeeper
      namespace: {{ default "bigbang" $.Values.namespace }}
    {{- end }}
    {{- if $kyvernoDep }}
    - name: kyvernopolicies
      namespace: {{ default "bigbang" $.Values.namespace }}
    {{- end }}
    {{- if $istioDep }}
    - name: istio
      namespace: {{ default "bigbang" $.Values.namespace }}
    {{- end -}}
  {{- end }}
---
{{ end -}}
{{- end -}}