{{- /* Used for deploying a package using Kustomize */ -}}
{{- range $pkg, $vals := .Values.packages -}}
{{- if and (dig "enabled" true $vals) $vals.kustomize -}}
{{- $pkg := include "resourceName" $pkg -}}
{{- $defaults := $.Files.Get (printf "defaults/%s.yaml" $pkg) -}}
{{- if $defaults -}}
{{- $vals := merge $vals ($defaults | fromYaml).package -}}
{{- end -}}
{{- $fluxSettings := merge (dig "flux" dict $vals) $.Values.flux -}}
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: {{ $pkg }}
  namespace: {{ dig "namespace" "name" $pkg $vals }}
  labels:
    app.kubernetes.io/name: {{ $pkg }}
    {{- include "commonLabels" $ | nindent 4 }}
spec:
  targetNamespace: {{ dig "namespace" "name" $pkg $vals }}
  interval: 10m
  path: {{ dig "git" "path" "" $vals }}
  sourceRef:
    kind: GitRepository
    name: {{ $pkg }}
    namespace: {{ dig "namespace" "name" $pkg $vals }}
  prune: true
  postBuild:
    substitute:
      # Package information
      package_name: {{ $pkg }}
      package_namespace: {{ dig "namespace" "name" $pkg $vals }}

      # Flux information
      flux_helm_release_path: "chart/"
      flux_helm_source_kind: "GitRepository"
      flux_helm_source_name: {{ $pkg }}
      flux_helm_source_namespace: {{ $pkg }}
      # Big Bang information
      bb_domain: {{ $.Values.domain }}
      bb_istio_enabled: "{{ $.Values.istio.enabled }}"
      bb_gateway: "public"
---
{{ end -}}
{{- end -}}