{{- $kyvernoOldPoliciesValues := default dict .Values.kyvernopolicies -}}
{{- $kyvernoNewPoliciesValues := default dict .Values.kyvernoPolicies -}}
{{- $kyvernoPoliciesValues := merge $kyvernoOldPoliciesValues $kyvernoNewPoliciesValues -}}
{{- $kyvernoOldReporterValues := default dict .Values.kyvernoreporter -}}
{{- $kyvernoNewReporterValues := default dict .Values.kyvernoReporter -}}
{{- $kyvernoReporterValues := merge $kyvernoOldReporterValues $kyvernoNewReporterValues -}}
{{- if or .Values.kyverno.enabled $kyvernoPoliciesValues.enabled $kyvernoReporterValues.enabled }}
{{- if ( include "imagePullSecret" . ) }}
apiVersion: v1
kind: Secret
metadata:
  name: private-registry
  namespace: kyverno
  labels:
    app.kubernetes.io/name: kyverno
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
{{- end }}