{{- $kyvernoOldPoliciesValues := default dict .Values.kyvernopolicies -}}
{{- $kyvernoNewPoliciesValues := default dict .Values.kyvernoPolicies -}}
{{- $kyvernoPoliciesValues := merge $kyvernoOldPoliciesValues $kyvernoNewPoliciesValues -}}
{{- $kyvernoOldReporterValues := default dict .Values.kyvernoreporter -}}
{{- $kyvernoNewReporterValues := default dict .Values.kyvernoReporter -}}
{{- $kyvernoReporterValues := merge $kyvernoOldReporterValues $kyvernoNewReporterValues -}}
{{- if or .Values.kyverno.enabled $kyvernoPoliciesValues.enabled $kyvernoReporterValues.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.kyverno "name" "kyverno" "defaults" (include "bigbang.defaults.kyverno" .)) }}
{{- end }}

{{- define "bigbang.defaults.kyverno" -}}
replicaCount: 3

image:
  pullSecrets:
  - name: private-registry
  pullPolicy: {{ .Values.imagePullPolicy }}

openshift: {{ .Values.openshift }}

networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}
  controlPlaneCidr: {{ .Values.networkPolicies.controlPlaneCidr }}

serviceMonitor:
  enabled: {{ .Values.monitoring.enabled }}
  dashboards:
    namespace: monitoring

istio:
  enabled: {{ .Values.istio.enabled }}
{{- end -}}
