{{- if .Values.addons.nexus.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: nexus-repository-manager
  labels:
    {{- if .Values.istio.enabled }}
    {{- end }}
    istio-injection: enabled
    app.kubernetes.io/name: "nexus-repository-manager"
    app.kubernetes.io/component: "developer-tools"
    {{- include "commonLabels" . | nindent 4}}
    istio-injection: {{ dig "istio" "injection" "enabled" .Values.addons.nexus }}
{{- end }}
