{{- if .Values.oci.enabled  }}
apiVersion: v1
kind: Secret
metadata:
  name: bigbang-oci-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }} 
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
