{{- if and (or .Values.loki.enabled .Values.promtail.enabled) (not .Values.logging.enabled) }}
apiVersion: v1
kind: Namespace
metadata:
  name: logging
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
    istio-injection: enabled
{{- end }}
