{{- if and .Values.monitoring.enabled (dig "grafana" "enabled" true .Values.monitoring.values) }}
apiVersion: v1
kind: Secret
metadata:
  name: grafana-auth
  namespace: monitoring
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
type: kubernetes.io/opaque
stringData:
  username: admin
{{- if (dig "grafana" "admin" "existingSecret" "" .Values.monitoring.values) }}
  {{- $passwordKey := (dig "grafana" "admin" "passwordKey" "admin-password" .Values.monitoring.values) }}
  {{- with lookup "v1" "Secret" "monitoring" .Values.monitoring.values.grafana.admin.existingSecret }}
  password: {{ (get .data $passwordKey | b64dec) | default "prom-operator" }}
  {{- end }}
{{- else }}
  password: {{ dig "grafana" "adminPassword" "prom-operator" .Values.monitoring.values }}
{{- end }}
{{- end }}