{{- if .Values.addons.podinfo.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: podinfo
  labels:
    istio-injection: enabled
    app.kubernetes.io/name: podinfo
    app.kubernetes.io/component: "application-utilities"
    {{- include "commonLabels" . | nindent 4}}
{{- end }}
