{{- $fluxSettingsHarbor := merge .Values.addons.harbor.flux .Values.flux -}}
{{- if .Values.addons.harbor.enabled }}
{{- $pkg := "harbor" }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ $pkg }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $pkg }}
    {{- include "commonLabels" . | nindent 4}}
  annotations:
    checksum/bigbang-values: {{ include (print $.Template.BasePath "/harbor/values.yaml") . | sha256sum }}
spec:
  releaseName: {{ $pkg }}
  targetNamespace: {{ $pkg }}
  chart:
    spec:
      {{- if eq .Values.addons.harbor.sourceType "git" }}
      chart: {{ .Values.addons.harbor.git.path }}
      sourceRef:
        kind: GitRepository
        name: harbor
        namespace: {{ .Release.Namespace }}
      {{- else }}
      chart: {{ .Values.addons.harbor.helmRepo.chartName }}
      version: {{ .Values.addons.harbor.helmRepo.tag }}
      sourceRef:
        kind: HelmRepository
        name: {{ .Values.addons.harbor.helmRepo.repoName }}
        namespace: {{ .Release.Namespace }}
      {{- end }}
      interval: 5m

  {{- toYaml $fluxSettingsHarbor | nindent 2 }}

  {{- if (get .Values $pkg).postRenderers }}
  postRenderers:
  {{ toYaml (get .Values $pkg).postRenderers | nindent 4 }}
  {{- end }}
  valuesFrom:
    - name: {{ .Release.Name }}-{{ $pkg }}-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-{{ $pkg }}-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-{{ $pkg }}-values
      kind: Secret
      valuesKey: "overlays"

  {{ if or .Values.istio.enabled }}
  dependsOn:
  {{- if .Values.istio.enabled }}
    - name: istio
      namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- end }}
{{- end }}