{{- $fluxSettingsArgoApps := merge .Values.addons.argocd-apps.flux .Values.flux -}}
{{- if .Values.addons.argocd.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argocd-apps
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: argocd-apps
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
spec:
  targetNamespace: argocd-apps
  chart:
    spec:
      {{- if eq (include "checkGitRef" .Values.addons.argocd) "true" }}
      chart: {{ .Values.addons.argocd-apps.git.path }}
      sourceRef:
        kind: GitRepository
        name: argocd-apps
        namespace: {{ .Release.Namespace }}
      {{- else }}
      chart: {{ .Values.addons.argocd-apps.oci.name }}
      version: {{ .Values.addons.argocd-apps.oci.tag }}
      sourceRef:
        kind: HelmRepository
        name: {{ .Values.addons.argocd-apps.oci.repo }}
        namespace: {{ .Release.Namespace }}
      {{- end }}
      interval: 5m

  {{- toYaml $fluxSettingsArgoApps | nindent 2 }}

  {{- if .Values.addons.argocd-apps.postRenderers }}
  postRenderers:
  {{ toYaml .Values.addons.argocd-apps.postRenderers | nindent 4 }}
  {{- end }}

  valuesFrom:
    - name: {{ .Release.Name }}-argocd-apps-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-argocd-apps-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-argocd-apps-values
      kind: Secret
      valuesKey: "overlays"

  {{- if or .Values.monitoring.enabled .Values.istio.enabled }}
  dependsOn:
  {{- if .Values.istio.enabled }}
  - name: istio
    namespace: {{ .Release.Namespace}}
  {{- end}}
  {{- if .Values.monitoring.enabled }}
  - name: monitoring
    namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- end }}
{{- end }}
