{{- if .Values.addons.jira.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: jira
  labels:
    app.kubernetes.io/name: jira
    app.kubernetes.io/component: "third-party"
    {{- include "commonLabels" . | nindent 4}}
    {{- if .Values.istio.enabled }}
    istio-injection: "enabled"
    {{- end }}
{{- end }}