{{- define "bigbang.defaults.jira" -}}
# hostname is deprecated and replaced with domain. But if hostname exists then use it.
domain: {{ default .Values.domain .Values.hostname }}
istio:
  enabled: {{ .Values.istio.enabled }}
  gateways:
    - istio-system/{{ default "public" .Values.addons.jira.ingress.gateway }}
monitoring:
  enabled: {{ .Values.monitoring.enabled }}
{{- end }}

{{- /* Create secret */ -}}
{{- if .Values.addons.jira.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.addons.jira "name" "jira" "defaults" (include "bigbang.defaults.jira" .)) }}
{{- end }}