{{- $eckOpOldValues := default dict .Values.eckoperator -}}
{{- $eckOpValues := merge $eckOpOldValues .Values.eckOperator -}}
{{- $logOldValues := default dict .Values.logging -}}
{{- $logValues := merge $logOldValues .Values.elasticsearchKibana -}}
{{- if and (eq (include "checkGitRef" $eckOpValues) "true") (not .Values.offline) (or $eckOpValues.enabled $logValues.enabled) }}
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: eck-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: eck-operator
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
spec:
  interval: {{ .Values.flux.interval }}
  url: {{ $eckOpValues.git.repo }}
  ref:
    {{- include "validRef" $eckOpValues.git | nindent 4 }}
  {{ include "gitIgnore" . }}
  {{- include "gitCreds" . | nindent 2 }}
{{- end }}
