{{- $eckOpOldValues := default dict .Values.eckoperator -}}
{{- $eckOpValues := merge $eckOpOldValues .Values.eckOperator -}}
{{- $logOldValues := default dict .Values.logging -}}
{{- $logValues := merge $logOldValues .Values.elasticsearchKibana -}}
{{- $fluxSettingsEckOperator := merge $eckOpValues.flux .Values.flux -}}
{{- if or $eckOpValues.enabled $logValues.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: eck-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: eck-operator
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
spec:
  targetNamespace: eck-operator
  chart:
    spec:
      {{- if eq (include "checkGitRef" $eckOpValues) "true" }}
      chart: {{ $eckOpValues.git.path }}
      sourceRef:
        kind: GitRepository
        name: eck-operator
        namespace: {{ .Release.Namespace }}
      {{- else }}
      chart: {{ $eckOpValues.oci.name }}
      version: {{ $eckOpValues.oci.tag }}
      sourceRef:
        kind: HelmRepository
        name: {{ $eckOpValues.oci.repo }}
        namespace: {{ .Release.Namespace }}
      {{- end }}
      interval: 5m

  {{- toYaml $fluxSettingsEckOperator | nindent 2 }}

  {{- if $eckOpValues.postRenderers }}
  postRenderers:
  {{ toYaml $eckOpValues.postRenderers | nindent 4 }}
  {{- end }}
  valuesFrom:
    - name: {{ .Release.Name }}-eck-operator-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-eck-operator-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-eck-operator-values
      kind: Secret
      valuesKey: "overlays"

  {{- if or .Values.gatekeeper.enabled .Values.istio.enabled .Values.kyvernopolicies.enabled }}
  dependsOn:
    {{- if .Values.gatekeeper.enabled }}
    - name: gatekeeper
      namespace: {{ .Release.Namespace }}
    {{- end }}
    {{- if .Values.istio.enabled }}
    - name: istio
      namespace: {{ .Release.Namespace }}
    {{- end }}
    {{- if .Values.kyvernopolicies.enabled }}
    - name: kyvernopolicies
      namespace: {{ .Release.Namespace }}
    {{- end }}
  {{- end }}
{{- end }}
