{{- $eckOpOldValues := default dict .Values.eckoperator -}}
{{- $eckOpValues := merge $eckOpOldValues .Values.eckOperator -}}
{{- $logOldValues := default dict .Values.logging -}}
{{- $logValues := merge $logOldValues .Values.elasticsearchKibana -}}
{{- if or $eckOpValues.enabled $logValues.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: eck-operator
  labels:
    app.kubernetes.io/name: eck-operator
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
    istio-injection: enabled
{{- end }}
