{{- $eckOpValues := .Values.eckOperator -}}
{{- $logValues := .Values.elasticsearchKibana -}}
{{- if or $eckOpValues.enabled $logValues.enabled }}
{{- include "values-secret" (dict "root" $ "package" $eckOpValues "name" "eck-operator" "defaults" (include "bigbang.defaults.eckOperator" .)) }}
{{- end }}

{{- $logValues := .Values.elasticsearchKibana -}}
{{- define "bigbang.defaults.eckOperator" -}}
license:
  trial: {{ $logValues.license.trial }}
  keyJSON: |
    {{ $logValues.license.keyJSON | nindent 4 }}

image:
  pullPolicy: {{ .Values.imagePullPolicy }}

{{- if .Values.istio.enabled }}
podAnnotations:
  traffic.sidecar.istio.io/includeInboundPorts: "*"
  traffic.sidecar.istio.io/excludeInboundPorts: "9443"
  {{ include "istioAnnotation" . }}
{{- end }}

openshift: {{ .Values.openshift }}

istio:
  enabled: {{ .Values.istio.enabled }}

monitoring:
  enabled: {{ .Values.monitoring.enabled }}

networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}
  controlPlaneCidr: {{ .Values.networkPolicies.controlPlaneCidr }}

imagePullSecrets:
  - name: private-registry
{{- end -}}
