{{- if .Values.grafana.enabled }}
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
spec:
  providerRef:
    name: grafana
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
      namespace: bigbang
{{- end }}
