{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: grafana-flux-auth
  namespace: monitoring
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
type: kubernetes.io/opaque
stringData:
{{- if (dig "admin" "existingSecret" "" .Values.grafana.values) }}
  {{- $passwordKey := (dig "admin" "passwordKey" "admin-password" .Values.grafana.values) }}
  {{- $userKey := (dig "admin" "userKey" "admin-user" .Values.grafana.values) }}
  {{- with lookup "v1" "Secret" "monitoring" .Values.grafana.values.admin.existingSecret }}
  username: {{ (get .data $userKey | b64dec) | default "admin" }}
  password: {{ (get .data $passwordKey | b64dec) | default "prom-operator" }}
  {{- end }}
{{- else }}
  username: {{ dig "adminUser" "admin" .Values.grafana.values }}
  password: {{ dig "adminPassword" "prom-operator" .Values.grafana.values }}
{{- end }}
{{- end }}
