{{- if .Values.grafana.enabled }}
{{- if or (and .Values.networkPolicies.enabled (dig "networkPolicies" "enabled" true .Values.grafana.values)) (and (not .Values.networkPolicies.enabled) (dig "networkPolicies" "enabled" false .Values.grafana.values)) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-flux
  namespace: monitoring
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: grafana
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: notification-controller
      namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: flux-system
    ports:
    - port: 3000
      protocol: TCP
{{- end }}
{{- end }}
