{{- if and (eq (include "checkGitRef" .Values.addons.mattermostOperator) "true") (not .Values.offline) (or .Values.addons.mattermostOperator.enabled .Values.addons.mattermost.enabled) }}
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: mattermost-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: mattermost-operator
    app.kubernetes.io/component: "collaboration-tools"
    {{- include "commonLabels" . | nindent 4}}
spec:
  interval: {{ .Values.flux.interval }}
  url: {{ .Values.addons.mattermostOperator.git.repo }}
  ref:
    {{- include "validRef" .Values.addons.mattermostOperator.git | nindent 4 }}
  {{ include "gitIgnore" . }}
  {{- include "gitCreds" . | nindent 2 }}
{{- end }}
