{{- if or .Values.addons.mattermostOperator.enabled .Values.addons.mattermost.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.addons.mattermostOperator "name" "mattermost-operator" "defaults" (include "bigbang.defaults.mattermostOperator" .)) }}
{{- end }}

{{- define "bigbang.defaults.mattermostOperator" -}}
imagePullSecrets:
  - name: private-registry

image:
  imagePullPolicy: {{ .Values.imagePullPolicy }}

{{- if .Values.istio.enabled }}
podAnnotations:
  {{ include "istioAnnotation" . }}
{{- end}}

networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}
  controlPlaneCidr: {{ .Values.networkPolicies.controlPlaneCidr }}

istio:
  enabled: {{ .Values.istio.enabled }}

monitoring:
  enabled: {{ .Values.monitoring.enabled }}

openshift: {{ .Values.openshift }}
{{- end -}}
