{{- $pkg := "holocron" }}
{{- if not (get .Values.addons $pkg).collectorAuth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: holocron-tokens
  namespace: {{ $pkg }}
  labels:
    app.kubernetes.io/name: {{ $pkg }}
    {{- include "commonLabels" . | nindent 4 }}
type: generic
data:
  gitlab-build-0: {{ (get .Values.addons $pkg).collectorAuth.gitlabToken | b64enc }}
  gitlab-scm-0: {{ (get .Values.addons $pkg).collectorAuth.gitlabToken | b64enc }}
  gitlab-workflow-0: {{ (get .Values.addons $pkg).collectorAuth.gitlabToken | b64enc }}
  jira-workflow-0: ""
---
{{- $pkg := "holocron" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: holocron-gitlab-job
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $pkg }}-gitlab-creds
    {{- include "commonLabels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh.hook-weight": "0"
    "helm.sh.hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: holocron-gitlab-job
      labels:
        app.kubernetes.io/name: {{ $pkg }}-gitlab-creds
        {{- include "commonLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
      - name: create-access-token
        image: registry1.dso.mil/ironbank/big-bang/base:2.0.0
        command:
        - /bin/sh
        - -ec
        - |
            TOOLBOX_POD="`kubectl get pod -n gitlab -l app=toolbox -o jsonpath='{.items[*].metadata.name}'`"
            kubectl exec -it -n gitlab $TOOLBOX_POD -- gitlab-rails runner "token = User.admins.first.personal_access_tokens.create(name: 'holocron', scopes: ['api'], expires_at: DateTime.now + 1); token.set_token({{ (get .Values.addons $pkg).collectorAuth.gitlabToken }}); token.save\!"
{{- end }}
