{{- $pkg := "holocron" }}
{{- if and (get .Values.addons $pkg).enabled (not (get .Values.addons $pkg).collectorAuth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: holocron-tokens
  namespace: {{ $pkg }}
  labels:
    app.kubernetes.io/name: {{ $pkg }}
    {{- include "commonLabels" . | nindent 4 }}
type: generic
data:
  {{- if .Values.addons.gitlab.enabled }}
  gitlab-build-0: {{ (get .Values.addons $pkg).collectorAuth.gitlabToken | b64enc }}
  gitlab-scm-0: {{ (get .Values.addons $pkg).collectorAuth.gitlabToken | b64enc }}
  gitlab-workflow-0: {{ (get .Values.addons $pkg).collectorAuth.gitlabToken | b64enc }}
  {{- end }}
  {{- if (get .Values.addons $pkg).jira.enabled }}
  jira-workflow-0: {{ (get .Values.addons $pkg).collectorAuth.jiraToken | b64enc }}
  {{- end }}
  {{- if .Values.addons.sonarqube.enabled }}
  sonar-analysis-0: {{ (get .Values.addons $pkg).collectorAuth.sonarToken | b64enc }}
  {{- end }}
{{- end }}
