{{- $pkg := "holocron" }}
apiVersion: v1
kind: Secret
metadata:
  name: holocron-tokens
  namespace: {{ $pkg }}
  labels:
    app.kubernetes.io/name: {{ $pkg }}
    {{- include "commonLabels" . |nindent 4 }}
type: generic
data:
  gitlab-build-0: ""
  gitlab-scm-0: ""
  gitlab-workflow-0: ""
  jira-workflow-0: ""
