{{- $pkg := "holocron" }}

{{- /* Create secret */ -}}
{{- if (get .Values.addons $pkg).enabled }}
{{- include "values-secret" (dict "root" $ "package" (get .Values.addons $pkg) "name" $pkg "defaults" (include (printf "bigbang.defaults.%s" $pkg) .)) }}
{{- end }}

{{- define "bigbang.defaults.holocron" -}}

imagePullSecrets:
- name: private-registry
imagePullPolicy: {{ .Values.imagePullPolicy }}

externalURL: https://holocron.{{ .Values.domain }}

domain: {{ .Values.domain }}

api:
  env:
    REQUEST_IP_HEADER: X-Forwarded-For
    SSO_ENABLED: {{ .Values.addons.holocron.sso.enabled }}
    SSO_ADMIN_GROUP: {{ .Values.addons.holocron.sso.groups.admin }}
    SSO_LEADERSHIP_GROUP: {{ .Values.addons.holocron.sso.groups.leadership }}
    SSO_GROUPS_KEY: group-full
    SSO_USERNAME_KEY: preferred_username

{{- if .Values.addons.gitlab.enabled }}
{{- $gitlabURL := "http://gitlab-webservice-default.gitlab.svc.cluster.local:8080" }}
collectorGitlabSCM:
- replicas: 1
  image:
    repository: registry1.dso.mil/ironbank/holocron/collector-gitlab-scm
    tag: "3.0.0"
    pullPolicy: IfNotPresent
  accessTokenSecretKey: gitlab-scm-0
  securityContext: {}
  resources: {}
  podAnnotations: {}
  env:
    GO_RUN_ENV: production
    COLLECTOR_NAME: gitlab-scm-0
    COLLECTOR_INTERVAL_SECONDS: 600
    LOOK_BACK_DAYS: 365
    TARGET_URL: {{ $gitlabURL }}
    COLLECTOR_TARGETS_INTRVL_SECS: 86400
    MAX_REQUESTS_PER_MINUTE: 500
collectorGitlabBuild:
- replicas: 1
  image:
    repository: registry1.dso.mil/ironbank/holocron/collector-gitlab-build
    tag: "3.0.0"
    pullPolicy: IfNotPresent
  accessTokenSecretKey: gitlab-build-0
  securityContext: {}
  resources: {}
  podAnnotations: {}
  env:
    GO_RUN_ENV: production
    COLLECTOR_NAME: gitlab-build-0
    COLLECTOR_INTERVAL_SECONDS: 600
    LOOK_BACK_DAYS: 365
    TARGET_URL: {{ $gitlabURL }}
    COLLECTOR_TARGETS_INTRVL_SECS: 86400
    MAX_REQUESTS_PER_MINUTE: 500
collectorGitlabWorkflow:
- replicas: 1
  image:
    repository: registry1.dso.mil/ironbank/holocron/collector-gitlab-workflow
    tag: "3.0.0"
    pullPolicy: IfNotPresent
  accessTokenSecretKey: gitlab-workflow-0
  securityContext: {}
  resources: {}
  podAnnotations: {}
  env:
    GO_RUN_ENV: production
    COLLECTOR_NAME: gitlab-workflow-0
    COLLECTOR_INTERVAL_SECONDS: 600
    LOOK_BACK_DAYS: 365
    TARGET_URL: {{ $gitlabURL }}
    COLLECTOR_TARGETS_INTRVL_SECS: 86400
    MAX_REQUESTS_PER_MINUTE: 500
    HIGHEST_PRIORITY_LABELS: priority::1,highest
    HIGH_PRIORITY_LABELS: priority::2,high
    MEDIUM_PRIORITY_LABELS: priority::3,medium
    LOW_PRIORITY_LABELS: priority::4,low
    LOWEST_PRIORITY_LABELS: priority::5,lowest
    DEFAULT_TICKET_PRIORITY: lowest
    FEATURE_LABELS: kind::feature,feature
    DEFECT_LABELS: kind::bug,kind::defect,bug,defect
    MAINTENANCE_LABELS: kind::maintenance,kind::docs,maintenance,docs,documentation
    UNPLANNED_LABELS: kind::unplanned
    DEFAULT_TICKET_TYPE: feature
{{- else }}
collectorGitlabSCM: []
collectorGitlabBuild: []
collectorGitlabWorkflow: []
{{- end }}
{{- if .Values.addons.holocron.jira.enabled }}
collectorJiraWorkflow:
- replicas: 1
  image:
    repository: registry1.dso.mil/ironbank/holocron/collector-jira-workflow
    tag: "3.0.0"
    pullPolicy: IfNotPresent
  accessTokenSecretKey: jira-workflow-0
  securityContext: {}
  resources: {}
  podAnnotations: {}
  env:
    GO_RUN_ENV: production
    COLLECTOR_NAME: collector-workflow-0
    COLLECTOR_INTERVAL_SECONDS: 600
    LOOK_BACK_DAYS: 365
    TARGET_URL: {{ .Values.addons.holocron.jira.service }}
    COLLECTOR_TARGETS_INTRVL_SECS: 86400
    MAX_REQUESTS_PER_MINUTE: 500
{{- else }}
collectorJiraWorkflow: []
{{- end }}
collectorSonarqubeProjectAnalysis: []

postgresql:
  {{- if .Values.addons.holocron.database.host }}
  enabled: false
  service:
    name: {{ .Values.addons.holocron.database.host }}
  {{- else }}
  enabled: true
  {{- end }}
  service:
    ports:
      postgresql: {{ .Values.addons.holocron.database.port }}
    
  image:
    repository: ironbank/opensource/postgres/postgresql
    tag: "15.4"
  auth:
    secretKey: password
    username: {{ .Values.addons.holocron.database.username }}
    password: {{ .Values.addons.holocron.database.password }}
    database: {{ .Values.addons.holocron.database.database }}
  tls:
    enabled: true
    autoGenerated: true

istio:
  enabled: {{ .Values.istio.enabled }}
  injection: enabled
  holocron:
    gateways:
    - istio-system/{{ default "public" .Values.addons.holocron.ingress.gateway }}
    hosts:
    - holocron.{{ .Values.domain }}

# networkPolicies:
#   enabled: {{ .Values.networkPolicies.enabled }}
#   egressHostLabels:
#     {{- if .Values.addons.gitlab.enabled }}
#     gitlab.com/webservice-name: default
#     {{- end }}
#     {{- if .Values.addons.holocron.jira.enabled }}
#     {{ toYaml .Values.addons.holocron.jira.service.label | nindent 4 }}
#     {{- end }}

networkPolicies:
  enabled: false

monitoring:
  enabled: {{ .Values.monitoring.enabled }}

{{- end }}
